language: node_js

node_js:
  - '12.14.0'

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

install:
  - yarn

before_script:
  - sleep 15

script:
  - docker-compose up
  - yarn test

before_deploy:
  - yarn build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
